### ISSUE TITLE
Refactorizar lógica de tema en componente individual

### ISSUE THREAD

**Issue by fabzio** [TinkuyWare/carpool-app-frontend#1]
export function Main() {
  const { switchTheme, themeChosen, theme } = useSelector(
    (state) => state.theme
  );
  const prefersDarkMode = usePrefersDarkMode();
  useEffect(() => {
    if (prefersDarkMode && theme === "light" && !themeChosen) {
      switchTheme();
    }
  }, [prefersDarkMode, switchTheme]);
  return (
    <div data-theme={theme} className="w-full h-svh ">
      <MainLayout>
        <SingUp />
      </MainLayout>
    </div>
  );
}

Convertir a componente "ThemeProvider" en nueva carpeta "contexts"

**Comment by Dalpb** [comment]
Hecho
